% $Author: DRTorresRuiz$
clear

%% SET UP VARIABLES
folder = ".\IC Ionto\13_128_Ionto\FRA\";
% folder = ".\IC Ionto\13_121_Ionto\FRA\";
output_folder = ".\neuronAnalysis";
year = 13;
animalID = "128";
% neuronNumber = 2;
neuronNumber = 1:7;
channels = 2;
levels = 0:10:80;

saveExcel = true;
showFigures = true;
showWarnings = false;
resetFigures = true;
resetConsole = true;

FRAConfiguration = struct(...
        "save", true,...
        "show", true,...
        "displayInfo", false,...
        "saveTXT", false,...
        "saveExcel", true,...
        "showPeriphery", true,...
        "showTitle", false,...
        "showCore", true,...
        "showBF", true,...
        "showCF", true,...
        "showSlopes", true,...
        "showFreq", true,...
        "cleanSA", true,...
        "figurePosition", [ 100 100 1000 800 ]);

PSTHConfiguration = struct(...
        "show", false,...
        "save", true,...
        "showDensityFunction", true,...
        "bins", [],...
        "figurePosition", [ 200 200 1000 800 ]);
    
SpikeRaster3DConfiguration = struct(...
        "show", false,...
        "showTitle", false,...
        "save", true,... 
        "saveGIF", true,...
        "cleanSA", true,...
        "figurePosition", [ 300 300 1000 800 ] );
    
FrequencyResponseProfileConfiguration = struct(...
        "show", true, ...
        "showTitle", false,...
        "save", true,...
        "figurePosition", [ 400 400 500 600 ]);


%% CALL MAIN FUNCTION
[stats, rf] = analyzeAuditoryNeuron( folder, year, animalID, neuronNumber, channels, levels,...
    FRAConfiguration, PSTHConfiguration, SpikeRaster3DConfiguration, FrequencyResponseProfileConfiguration, ...
    output_folder, showFigures, saveExcel, showWarnings, resetFigures, resetConsole );
